config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tasks#index"

  resources :tasks
  resources :lists, only: [:new, :create, :edit, :update, :destroy] do
    resources :cards, except: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  validates :title, length: { in: 1..255 }
  validates :memo, length: { maximum: 1000 }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  has_many :cards, dependent: :destroy

  validates :title, length: { in: 1..255 }
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :lists, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only:[:edit, :update, :show, :destroy]

  def new
    @list = List.find_by(id: params[:list_id])
    @card = Card.new
  end
  
  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit
    @lists = List.where(user: current_user)
  end
  
  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end
  
  def show
  end

  def destroy
    @card.destroy
    redirect_to :root
  end
  
  private
  def card_params
    params.require(:card).permit(:title, :memo, :list_id)
  end
  
  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit
  end
  
  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end
  
  def destroy
    redirect_to :root if @list.destroy
  end
  
  private
  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end
  
  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/edit.html.haml
.cardeditPgae
  .container
    = form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f|
      - if @card.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      .cardeditForm_title
        = f.label :title
        = f.text_field :title, class: "form-control", placeholder: "カード名"
      .cardeditForm_memo
        = f.label :memo
        = f.text_area :memo, class: "form-control", placeholder: "詳細"
      .cardeditForm_memo
        %label リスト名
        = select :card, :list_id, @lists.map{ |list| [list.title, list.id] }, {}, { class: 'form-control' }
      .text-center= f.submit "更新する", class: "submitBtn"

app/views/cards/new.html.haml
.cardnewPgae
  .container
    = form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f|
      = f.hidden_field :list_id, value: @list.id
      - if @card.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      .cardnewForm_title
        = f.label :title
        = f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名"
      .cardnewForm_memo
        = f.label :memo
        = f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細"
        .text-center= f.submit "作成する", class: "submitBtn"

app/views/cards/show.html.haml
.carddetailPage
  .container
    .cardContents
      .cardContents_title
        %div タイトル
        %h2= @card.title
      .cardContents_memo
        %div メモ
        %div= @card.memo
      .cardContents_listStatus
        %div リスト名
        %div= @card.list.title
      .cardContents_btnArea
        = link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn"
        = link_to '削除をする', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FocusON
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'partial/header' if current_user
    - if flash[:notice]
      %div{class: "alert alert-info"}
        = flash[:notice]
    - if flash[:alert]
      %div{class: "alert alert-danger"}
        = flash[:alert]

    = yield

app/views/lists/edit.html.haml
.listeditPage
  .container
    = form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f|
      - if @list.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      = f.label :title
      = f.text_field :title, class: "form-control listName", placeholder: "リスト名"
      .text-center= f.submit "編集する", class: "submitBtn"

app/views/lists/new.html.haml
.listnewPage
  .container
    = form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f|
      - if @list.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      = f.label :title
      = f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名"
      .text-center= f.submit "作成", class: "submitBtn"

app/views/partial/_header.html.haml
%header.header
  %nav.nav
    %ul.header_menu
      %li.nav-link
        = "#{current_user.name} さん"
      %li.header_menu_title
        = link_to "FocusON", root_path, class: "nav-link"
      %li
        %ul.header_menu_inner
          %li
            = link_to new_list_path, class: "nav-link" do
              %span.mr-1 リストを作成
          %li
            = link_to "サインアウト", destroy_user_session_path, method: :delete, class: "nav-link"

app/views/tasks/index.html.haml
.topPage
  .listWrapper
    - @lists.each do |list|
      .list
        .list_header
          %h2.list_header_title= list.title
          .list_header_action
            = link_to "削除", list_path(list), method: :delete, class: "delete_link", data: { confirm: "#{list.title}を削除して大丈夫ですか？" }
            = link_to "編集", edit_list_path(list), class: "edit_link"
        .cardWrapper
          - list.cards.each do |card|
            = link_to list_card_path(list, card), class:"cardDetail_link" do
              .card
                %h3.card_title
                  = card.title
                - if card.memo.size > 0
                  %div{class: "card_detail is-exist"}
                    %i{class: "fas fa-bars"}
          .addCard
            = link_to "さらにカードを追加", new_list_card_path(list.id), class: "addCard_link"
  %p 最終アクセス日時：
  %span#time